### PR TITLE
Issue/undefined container

### LINKED ISSUE #5: TypeError: Cannot read property 'appendChild' of null
This exception is happening inside `image.js` and I'm wondering if it's due to the fact that my `<Image>` element is conditionally-rendered? The image does end up loading properly, but I do see this error in the console.

```
image.js:257 Uncaught (in promise) TypeError: Cannot read property 'appendChild' of null
    at Image.<anonymous> (image.js:257)
    at step (image.js:151)
    at Object.next (image.js:81)
    at fulfilled (image.js:33) 
```

### PR DESCRIPTION
**Pull request by ksstott**
Fixes #5

### CODE REVIEW

**Comment by Jameskmonger** [comment]
although @ksstott you may want to just return early from that function if `this.container` is null, to prevent needlessly rendering to a canvas

**Comment by ksstott** [comment]
> although @ksstott you may want to just return early from that function if `this.container` is null, to prevent needlessly rendering to a canvas

It's more complicated than that though. `this.container` only becomes null **after** the `await`. Unless I've misunderstood what you meant.

**Comment by Jameskmonger** [comment]
> It's more complicated than that though. `this.container` only becomes null **after** the `await`. Unless I've misunderstood what you meant.

weird! good catch

**Comment by hisuwh** [comment]
@ksstott if I merge this do you think you can look at publishing it? Do you have an npm account?

**Comment by ksstott** [comment]
> @ksstott if I merge this do you think you can look at publishing it? Do you have an npm account?

@hisuwh Yes I can do that.
no, someone will need to show me/give me access to publishing to npm please

**Pull request merged**
